# Academics {#sec-academics}

First, it's important to recognize that **you are responsible for your degree**. This means, ultimately, you need to stay on top of program and university deadlines, requirements, etc.

The [Office of Research and Graduate Studies](https://pharmacy.ufl.edu/research/research-and-graduate-studies/) and [POP Policies and Procedures Manual](https://pop.pharmacy.ufl.edu/education/resources-links/) should be the first ports of call for information about program requirements, and what needs to be done when. The [Milestones document](https://pop.pharmacy.ufl.edu/people/students/forms-and-templates/) will be critical for you to ensure you're making progress and on track to graduate in a reasonable time frame

## PhD Students

### Registration

Academic credit registration management in our program is done through the COP Office of Research and Graduate Studies. Registration for each semester takes place about mid-way (sometimes slightly later) through the previous semester and you will receive communication from the Graduate Coordinator for the department on deadlines. It is critical to register promptly to facilitate faculty and institutional planning (and avoid late registration fees). Before registering for each semester, you should meet with Dr. Smith to review your milestone document and discuss registration plans for the forthcoming semester (courses and/or research credits, etc). See [Chapter @sec-courses] for details on courses available to POP graduate students.  

Course of study should be selected with the program requirements in mind - but remember that electives are built in, and these should be tailored towards the skills you hope to leave the PhD program with. 
  
Most students take their core program requirements in the first 1-2 years. Depending on course availability, it is possible coursework may extend into year 3. **Keep in mind that required courses, including college-wide courses, are required** unless you receive explicit approval to skip these.   

Starting primarily in year 3 (sometimes year 2), most students will take 3-6 hours (possibly more) of research credits. Prior to beginning work on your dissertation, these courses will be independent research courses requiring independent research projects. Such projects are developed **by the student** in coordination with Dr. Smith. Deliverables must be declared when signing up for the credits, and it's important that students consider what is feasible in a semester and propose deliverables accordingly. Later in year 3, and especially in year 4, the shift will be towards advanced research credits while students devote time to thesis work.

**Thesis credits**: Thesis credits are required for both MS and PhD degrees. It is your responsibility to understand credit requirements, particularly for thesis credits. Once thesis and dissertation credit requirements have been met, MS and PhD students will often maintain registration through 'continuation of program' credit, where no credits are earned but enrollment status is maintained.  

### Dissertation

You should aim to complete your dissertation within ~4 years of starting the program. Coursework will largely be completed by end of year ~2, giving you ~2 years to complete dissertation work. Keep in mind that the Department typically only guarantees funding for 4 years. A major barrier to completing the PhD in 4 years is a lag time between completing coursework and settling on dissertation aims and completing the written qualifying exam. So, be thinking about your dissertation no later than year 2, so you have a plan entering year 3.

#### Timeline

##### Year 1 {.unnumbered}

Your dissertation work begins in Year 1, when you begin to form your committee. In fact, you need to have your internal committee in place by the end of year 1 of the program. So, you should be meeting with other faculty in the graduate program to identify potential members of your committee (don't worry, we can change these later as the dissertation takes form). 

Also in Year 1, you will need to declare a specialization. If you're in our lab, this is likely pharmacoepidemiology, or possibly health services research. 

##### Year 2 {.unnumbered}

By end of year 2, you need to have your full committee (≥3 internal members + ≥1 external) in place, including the external member. The external member should be identified by you, but certainly discuss options with Dr. Smith. Often, the external committee member will be someone with clinical expertise in the dissertation topic. Sometimes, it will be someone with methdologic expertise, but this is less common because often such expertise can be found in the department (thus, from internal members of the committee). It is also possible to identify a clinical collaborator who is not necessarily a member of your committee, but who may contribute to your dissertation science. 

By end of year 2, you should also be making significant progress on your dissertation aims. These need not necessarily be set in stone by end of year 2, but you should have a topic, and a general idea of what your dissertation will look like. 

Finally, you will have taken and (hopefully) passed your pre-qualifying exam. This is a 2-day exam comprised of 4 sections (policy, study design, analysis, and a manuscript review). If you did not pass, you will need to remediate the section(s) not passed. Successful remediation is required to progress further in the program. Obviously, discuss this with Dr. Smith, so we can make sure you are successful in remediation. 

##### Year 3 {.unnumbered}

Your coursework should be largely completed, and your dissertation topic should be solidified. Your written qualifying exam should be at least scheduled by Fall of year 3 (presuming you passed the preliminary exam), and completed by fall or spring semester. Ideally, **you should submit an extramural grant in late fall/spring semester** based on your dissertation work.

##### Year 4 {.unnumbered}

You should schedule and pass your oral qualifying exam. This year is spent on your dissertation. 

##### Year 5, as needed {.unnumbered}

You should complete your dissertation and defend. Funding for this year is not guaranteed and dependent on progress towards your defense. Funding beyond this year is highly unlikely.

#### What does your committee look like?

Your PhD thesis committee serves as your guidance team during your research, and should be viewed as colleagues and collaborators. There is a required minimum for interaction with the committee, but you try to go above and beyond this. After you have formed the committee, it is advisable to hold a committee meeting at least once a year, but it is encouraged to continually interact with committee members as needs arise with developing/executing the project.

While building your thesis ideas, discuss with Dr. Smith. For PhD committees, four members is the usual size, though some students will have a fifth member. Generally in our program a committee will be made up of your advisor (Dr. Smith), two additional COP graduate faculty members (note that these will generally be POP faculty, but could be other COP graduate faculty and sometimes even members from other colleges who hold POP graduate faculty status), and ~1 external member (most often someone with clinical expertise in the dissertation topic). Aim to hold your first committee meeting no later than during the Winter of your 2nd year. 

#### What is expected of committee meetings? 

This depends largely on where you're at in the program. During the first meeting, you should bring everyone up to speed on your background, your progress through the program, and your thoughts for your dissertation topic and specific aims. It's likely you'll receive feedback that alters these aims to some degree -- but that's normal and okay. As committee meetings progress, we expect that your presentations will similarly progress. Nitty gritty details/problems/barriers are best reserved for individual meetings with committee members or with the lab group. These full committee meetings should really be focused on 'big-picture' accomplishments and issues as you progress through your PhD program. Some of these members you may not have a lot of access to -- what do you really want them to give you feedback on during these meetings?  

#### What does your **proposal** look like? 

A proposal describing the research that will comprise the dissertation is a required, formal part of the academic program. Proposals should describe the goals and themes of the research to be conducted, and its context within current state of knowledge. The proposal should outline the research questions that each chapter (or paper) will address, and give a description of the methods that will be used in each. The proposal serves as a guiding document for the remainder of your program and is the document that you and your committee will use to agree on the scope of work to be completed to fulfill the degree requirements. Your thesis proposal should contain a literature review, identification of research questions, an overview of the methods that will be used for each of these, and description of expected results and relevance/significance of the research. Aim for the proposal to be  up to 12 pages of text. Detail of planning for each chapter will not be as comprehensive (it is expected that later chapters may not be as fleshed out), but the proposal should provide enough detail of what the student will do for the committee to evaluate whether the scope of work is sufficient (and likely make recommendations for reducing or refining this). It is common for students to have completed or be close to having completed work for at least one of the chapters by the time of defending the proposal.  
Ultimately, the proposal serves to clarify and outline expectations for the degree for both the student and the thesis committee, and serves as a blueprint for building out the thesis itself (indeed you will re-use some of the text later).  

#### What does your **dissertation** ultimately look like? 

You have two options: a conventional dissertation, or three papers. Most students in our program choose the three papers, but the choice is yours. If you choose 3 papers, that means that we expect you to actually submit and publish (at least) 3 papers from your dissertation work. And, the Graduate School will still require you put together a [formal dissertation report](http://graduateschool.ufl.edu/about-us/offices/editorial/format-requirements/). Good news is you'll have access to plenty of examples of this from students and former grads in our program.

## MS students

Thesis Proposal: MS students prepare a thesis proposal during their first year to identify and refine their thesis research topic ideas and outline methods that will be used to address the research questions. The proposal also serves as a guiding document for your initial committee meeting(s). Your committee only requires internal members (i.e., faculty in the department). Scope and plans for the MS thesis research will be developed through your meetings with Dr. Smith and with the project team (for students whose work is being funded by a research grant). Your thesis proposal should contain a literature review, identification of research questions, an overview of the methods that will be used, and description of expected results and relevance/significance of the research. Aim for the proposal to be about 8 pages of text. While not a formal requirement, a MS thesis proposal serves to clarify and outline expectations for the degree for both the student and the thesis committee, and serves as a blueprint for building out the thesis itself (indeed you may likely re-use some of the text later if you pursue a PhD). Thesis proposals written by other MS students in the Department are good examples of how these documents can be structured. 

## Rolling with the punches...

Remember, not everything will go to plan and your interests may change, not to mention your early findings may alter your research plan -- that's science. Contents of your thesis proposal are not set in stone and can always be revised with communication and collaboration with the committee. View proposals as items that help you build your scientific products rather than evaluative procedures that need to be checked off.  