# Communication {#sec-communication}


Good communication in our field is critical, both in terms of communicating with each other and other collaborators, as well as communicating our work, its reach and its limitations. 

Work on engaging with others about your work. This includes communication with the lab team, your peers, collaborators, and also communicating your work to others. This effort will pay off in many ways, but perhaps most importantly, it makes you a known quantity -- and that's good for getting opportunities (including jobs!).

If someone works on something for you or provides you with feedback on your work, thank them and engage with them on their feedback. Our science improves by engaging with conversations about your work. View such interactions as opportunities to be collaborative rather than evaluative. Chances are if someone asks you questions about your work it is because they are interested in your science.   

While publishing and conference presentations will continue as standard forms in which science is disseminated, there are a number of ways in which you can communicate your work with others, depending on your audiences and chosen levels of engagement. You should always invest in these at the level that is of interest to you. Below are some things to consider.  

## Curriculum Vitae

Keep your CV up to date, ideally as things happen (easier to remember right away than once a year, etc..). We share our CVs within the group in the CVmedLab Dropbox Folder (ask Dr. Smith if you don't have access), both to give each other ideas about what to include, but also having these in one place makes it easier for Dr. Smith and others to reference information from them when needed.  

There's no universal approach to CVs, and your CV will change over time, as you gain experience, and as the emphasis of your career changes. The [UF Career Center](https://career.ufl.edu/resumes-documents/cvs/) has some guidance for constructing your CV, but don't feel like it's absolutely necessary to follow their templates. The important thing is that it's well-organized, clean (not cluttered), and makes use of white space. Finally, be careful about how much personal information you put on there, as your CV will be shared beyond those who you specifically send it to. You can always supplement personal information in an email or job application, but you probably don't want your home address or cell phone # out there for everyone to see. If you feel like you need a number, sign up for a [Google Voice](https://voice.google.com/) number that will mask your real cell number. 

## ORCiD

Before you submit your first paper, you should set up an [ORCiD](https://orcid.org/), which is a persistent digital identifier for you. More importantly, many/most journals will allow you to link your ORCiD to your paper, so that you have a persistent record of all your published papers, and (particularly if you share a name with others), it allows you to distinguish yourself from other researchers of the same or similar name. 

## PubMed Profile

Once you have your first publication in a peer-reviewed journal, you should set up a [PubMed profile](https://account.ncbi.nlm.nih.gov/). With this account, you can track publications and add them to your PubMed bibliography, a persistent list of all your publications. PubMed also has a nifty Biosketch tool, for when you need to start creating Biosketches. 

## Google Scholar profiles

Having a [Google Scholar](https://scholar.google.com/) profile is a very easy way to curate your web presence and have a place where people can find you and your published papers and reports.  

We recommend everyone sets up a Google Scholar profile as soon as they have a paper or technical report. It takes about 5-10 minutes to set up, and one advantage is that Google Scholar self-updates and will add your papers and citations as you publish and people use your work. This is a really easy step to creating a web presence without having to set up a website. Note though that you need to check your profile periodically, as Google attributes articles to you incorrectly fairly often, particularly if you have a common name. 

## Personal Websites

### Why have your own website?

1. People will Google you. They might as well see what you want them to.
2. Give people an easy way to find you and your work.
3. It will set you apart from the myriad other researchers who just have a (often half-baked) LinkedIn profile. 

One way to do this is a personal website. This doesn't have to be extensive, but can be a good way to curate your web presence.  

There are heaps of tools out there to create and publish websites. Our recommendation is to choose something that it is easy to update, and fun / interesting for you to use. Many good options are free.

Some options for creating sites include: 

-   [Github](https://github.com/) (what [this website](https://github.com/cvmedlab) uses!)
-   [Google Sites](https://sites.google.com/)
-   [Weebly](https://www.weebly.com/)
-   [Squarespace](https://www.squarespace.com/)
-   [WordPress](https://wordpress.com/)
-   [Wix](https://www.wix.com/)

### What should you include?

Ultimately this is up to you and how you would like to present yourself and your work. But some common things you could include are:

-   CV or Biosketch
-   Research interests/overview/expertise
-   Projects, including your roles
-   Publications
-   Blog posts
-   Contact info

An example website (though many amazing others exist and you should check those out): [Dr. Smith's website on github](https://stevenmsmith.org/) made with [Quarto](https://quarto.org/). 

If you create your own, please let Dr. Smith know so he can link to it as well.

## Twitter or Similar

Twitter is (or at least, was) a great tool for interacting with others about your science. It is also a great platform for learning about new research and papers, finding out about jobs and fellowships, learning and discussing methods, discussing topics about how we do science, professional development, mental health and expectations around science and graduate school, and is a great venue for bringing ones whole self to the science. etc. Most of us have our own personal Twitter accounts and use them to varying degress. Everyone in the lab can post to the lab Twitter account too. Ask Dr. Smith if you are interested in doing a takeover of [CVmedLab](https://twitter.com/CVmedLab) account for a week (which could also be a chance to dip your toe in to Twitter if you don't use it).  

In addition to twitter, some users prefer Mastodon, which has some similarities to Twitter, but also some significant differences. The biggest difference is that there's a lot of different iterations of Mastodon, depending on your interest. For example, [Fosstodon](https://fosstodon.org) has a lot of data science, statistics, and other data-driven researchers. 

## Other Social Media

As you know, there are many social media platforms, and many (all?) of these are being used in some way for science communication. This includes but not limited to: 

-   Twitter
-   Instagram
-   Facebook
-   LinkedIn
-   TikTok
-   YouTube
-   ResearchGate

All have a different purpose and type of engagement. Think deliberately about how (and if) you want to use these tools. Using social media as part of your science communication portfolio can be useful and is popular, but it is not a requirement to be a successful scientist. And, keep in mind, these can often be deleterious to your mental health. Use them wisely, if at all. 
