# Lab culture and philosophy {#sec-culture}


> **telos**\
> the purpose, end, or goal of an entity

Our *telos* is truth. That means we pursue excellence in science - with the goal of finding truth foremost. But, we hold a lot of additional secondary goals. As part of our core lab culture, we (in no particular order):

-   **Ask for help, and share our learning**
-   **Make ourselves available (within reason)**
-   **Come prepared and engage**
-   **Celebrate accomplishments (ours & those of others)**
-   **Sustain a positive, safe learning environment**
-   **Have an interdisciplinary (open) mindset**
-   **Are mindful of our own biases**
-   **Plan with intention, and follow through**
-   **Foster inclusivity within our group and greater community**
-   **Promote and sustain healthy work-life integration**
-   **Acknowledge, celebrate, and give credit to other lab member's work**

Though we do not expect incoming members to memorize everything, we do expect members to be aware of the group's values.

## Ask for help, and share your learning {#sec-ask_for_help}

We are all learners, and most of our learning is done from each other. It is inefficient to struggle through problems alone. Take advantage of the team, as well as the larger POP and COP graduate programs. Ask for and give assistance with appropriate cognizance of the value of your time and the time of the person you are asking. You are not the first or last person to encounter a problem. When you identify a problem, make it known to the lab if you need help, and update it with solutions when it is resolved. Also consider writing a tutorial/blog post for inclusion in our [lab's "lab docs"](https://cvmedlab.org/), and share with the rest of the lab. Just showing us how you overcame a challenge is often an important step for stimulating others to think about how they'd approach the same challenge

## Make yourself available

Be responsive to communication, and make time for things that address longer term goals, even when busy. For example, do not skip on things like attending seminars just because you have a big deadline looming (see note below on planning and organization). Note that being available does not mean that you are available 24/7 - this is not expected. Because as a group we value the role of collaboration and interaction in improving our work, it is expected that you be available in the office/campus during normal business hours for some time during the week (see section on attendance expectations).

## Come prepared and be engaged {#sec-come_prepared}

Value your time. Be present during lab and individual meetings, and come to your work ready to do your work. Contribute and participate in planning and lab discussions. When it is your turn to run a meeting, come with an agenda and be prepared with questions. Aim to view meetings as events that contribute to your work and productivity, rather than taking away from them. If something unexpected comes up, and you are just completely unprepared to have a meeting, try to find someone else to run group meetings, or for 1:1 meetings, let Dr. Smith know if you need to cancel. 

## Celebrate accomplishments (yours & others')

You and your colleagues work hard. Things don't always go exactly as planned. Be supportive and proud of yourself and your peers when you accomplish things. We are not competing with each other - someone else's success does not mean your failure. Share your accomplishments with others!

## Sustain a positive, safe learning environment

We're here to learn and grow as scientists. Everyone learns something for the first time at some time, and people learn in different ways. Expressing that you don't know something is OK - good, even! - this is a University after all. Nevertheless, we understand that this can make you feel vulnerable. We strive to maintain a culture that allows for and encourages this vulnerability. Community members should not be disparaged for not knowing things, and in addition, should not be disparaged for knowing things or wanting to learn. That's precisely why we're all here.

## Have an interdisciplinary (open) mindset

It's quite rare that any one person has the necessary clinical and methodologic expertise to go at a project alone. It's even rare that a single person has the necessary experience/knowledge to sufficiently cover one of those arms. We collaborate, both within the CVmedLab, as well as outside it, because we most often work on problems that span multiple disciplines. Co-creation of knowledge requires transdisciplinary approaches that can result in solutions that would not be possible with siloing. You will be collaborating with others who have different types of expertise, values, and terminology. Trust the expertise of others and actively seek feedback recognizing the importance of specialization.

## Be mindful and aware of your own biases

We all have biases that are inherent and can not be removed, but we can still work on both being less biased, and more aware of bias in ourselves and others. 

## Plan with intention, and follow through

Be organized and adaptable. Things don't always go as planned and that's OK. Planning can help you adapt when they don't (see @sec-come_prepared). Find a program/project management approach that works for you (see @sec-intro); being organized can reduce stress immensely and help you progress with your goals.

## Foster inclusivity within our group and greater community

Part of our lab culture is that we are good citizens of our community, we take on leadership roles, when feasible, within UFCOP and the University, we are supportive of others in our community during their milestones, we actively participate in COP/POP events (e.g., seminar, college talks, etc) and perform outreach. Work with Dr. Smith when crafting your individual mentoring/development plans (see @sec-onboarding) to identify what you want to (re-)aim your efforts at.

## Promote and sustain healthy work-life integration

Our scientific research is not the only important thing in our lives, and publishing research is not the only mechanism by which to provide science and support our communities. We recognize the importance of our other commitments in keeping us healthy (mentally and physically) and bring our whole selves to our efforts. Try not to normalize overwork or being busy as achievement or status. Plan downtime for yourself to recuperate. Take time off during the summer. Work is work - it's not you're entire life. 

## Acknowledge and give credit

Working as part of a team, we will almost always be building on work done by others, receive assistance with work (see @sec-ask_for_help), and using others' words, code, philosophy, or content. Include acknowledgement and give credit for those contributions, in all forms of communication. We share content and code within the group with this expectation. One easy approach is to include hyperlinks to the work of others or their social media in your work. This also helps to amplify their work (and voice) as well as yours.
